 * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
127.0.0.1 - - [29/Oct/2017 04:28:43] "GET /schedule HTTP/1.1" 200 -
[2017-10-29 04:28:46,384] ERROR in app: Exception on /add-task [POST]
Traceback (most recent call last):
  File "/home/tool/flaskproject/venv/lib/python3.5/site-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/tool/flaskproject/venv/lib/python3.5/site-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/tool/flaskproject/venv/lib/python3.5/site-packages/flask_cors/extension.py", line 161, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/home/tool/flaskproject/venv/lib/python3.5/site-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/tool/flaskproject/venv/lib/python3.5/site-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/home/tool/flaskproject/venv/lib/python3.5/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/tool/flaskproject/venv/lib/python3.5/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "app.py", line 27, in add_task
    task_manager.add_task(request.json['name'], int(request.json['duration']))
  File "/home/tool/flaskproject/task.py", line 17, in add_task
    self.next_break = start_time + timedelta(minutes=self.break_gap)
TypeError: unsupported type for timedelta minutes component: datetime.timedelta
127.0.0.1 - - [29/Oct/2017 04:28:46] "POST /add-task HTTP/1.1" 500 -
